Repository SAP/fosstars-rating-core, pull requests merged in 2020-03, with the labels that each got.

#52 Updated ScoreValue to store a list of used values
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Confidence.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/AbstractVerifier.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/AbstractScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/WeightedCompositeScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/example/ProjectActivityScoreExample.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/example/SecurityTestingScoreExample.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/CommunityCommitmentScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/LgtmScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectPopularityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/RatingValue.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/ScoreValue.java
  src/test/java/com/sap/sgs/phosphor/fosstars/TestUtils.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/WeightedCompositeScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/CommunityCommitmentScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/LgtmScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreVerification.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectPopularityScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/RatingValueTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/ScoreValueTest.java
Labels: enhancement

#57 Renamed SecurityLabel.OKAY to SecurityLabel.MODERATE
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRating.java
Labels: enhancement

#64 Introduced DependencyScanScore
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScore.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScoreTestVectors.csv
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScoreVerification.java
Labels: enhancement

#66 Implement a DataProvider to generate feature USES_VERIFIED_SIGNED_COMMITS
  README.md
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommits.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculator.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitFalse.json
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitTrue.json
Labels: enhancement

#75 Changed relative to absolute links to work with gh-pages
  docs/oss_security_rating.md
Labels: documentation

#83 Updated Jackson to 2.10.3
  pom.xml
Labels: dependency
