Repository SAP/fosstars-rating-core, pull requests merged in 2020-05, with the labels that each got.

#167 Update UsesOwaspDependencyCheck to support Gradle
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyCheckTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/GradleWithOwaspDependencyCheck.gradle
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/GradleWithoutOwaspDependencyCheck.gradle
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/MavenWithOwaspDependencyCheckInBuild.xml
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/MavenWithOwaspDependencyCheckInReporting.xml
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/MavenWithoutOwaspDependencyCheck.xml
Labels: enhancement

#166 GitHubProjectFinder should take into account number of stars
  docs/oss/security/apache.yml
  docs/oss/security/eclipse.yml
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProjectFinder.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProjectFinderTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculatorTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/tool/github/ValidProjectFinderConfig.yml
Labels: enhancement

#181 NVD.parse() sometimes parses too much
  src/main/java/com/sap/sgs/phosphor/fosstars/nvd/NVD.java
Labels: bug

#183 VulnerabilityLifetimeScore should not break when dates are incorrect
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/AbstractScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScore.java
Labels: bug

#185 UsesGithubForDevelopment should not divide integers
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopment.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopmentTest.java
Labels: bug

#180 Improve vulnerability matching
  pom.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NvdEntryMatcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/nvd/data/Node.java
  src/test/java/com/sap/sgs/phosphor/fosstars/nvd/NVDTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/nvd/NVD_matcher.json
Labels: dependency, enhancement

#197 Make documentation great again
  README.md
  docs/confidence.md
  docs/example.md
  docs/oss_security_rating.md
  docs/oss_security_rating.plantuml
  docs/oss_security_rating.png
  docs/qa.md
  docs/rating_score_feature_hierarchy.plantuml
  docs/rating_score_feature_hierarchy.png
  docs/ratings.md
  docs/tuning.md
Labels: documentation

#198 HasSecurityTeam data provider always returns unknown
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityTeam.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityTeamTest.java
Labels: bug

#199 Removed rating versions
  checkstyle-suppressions.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Rating.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/RatingRepository.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Version.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/AbstractRating.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExample.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExampleTuningWithCMAES.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRating.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExample_1_1.json
  src/test/java/com/sap/sgs/phosphor/fosstars/model/RatingRepositoryTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExampleTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTest.java
Labels: enhancement

#201 Relative thresholds for labels in the OSS security rating
  src/main/java/com/sap/sgs/phosphor/fosstars/model/RatingRepository.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRating.java
  src/main/jupyter/oss/security/SecurityRatingAnalysis.ipynb
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingThresholds.json
  src/test/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTest.java
Labels: enhancement

#200 UsesGitHubForDevelopment data provider seems to provide false-positives
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopment.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopmentTest.java
Labels: bug

#207 Fixes ConcurrentModificationException issue in GitHubDataFetcher
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java
Labels: bug
