Repository SAP/fosstars-rating-core, pull requests merged in 2020-08, with the labels that each got.

#302 Switch from CLA to DCO and use the REUSE tool
  .reuse/dep5
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  NOTICE
  README.md
  SAP_CCLA.pdf
Labels: documentation

#317 Closing InputStream with try-with-resources block
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/FuzzedInOssFuzz.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java
Labels: bug

#306 Update the tool to accept GAV
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProject.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MavenScmFinder.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculator.java
Labels: enhancement

#312 Added Google Lighthouse to the report
  docs/oss/security/GoogleChrome/lighthouse.md
  docs/oss/security/other.yml
Labels: documentation

#314 Fix several formatting issues in PrettyPrinter
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/format/PrettyPrinter.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/format/PrettyPrinterTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/MarkdownReporterTest.java
Labels: enhancement

#327 Added a score for Dependabot
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependabotScore.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/DependabotScoreTestVectors.yml
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependabotScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependabotScoreVerification.java
Labels: enhancement
