Repository SAP/fosstars-rating-core, pull requests merged in 2020-04, with the labels that each got.

#105 Store test vectors in YAML
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/AbstractVerification.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingVerification.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/CommunityCommitmentScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/LgtmScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectPopularityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/DateValue.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/Vulnerability.java
  src/main/jupyter/oss/security/CommunityCommitmentScoreTestVectors.ipynb
  src/main/jupyter/oss/security/LgtmScoreTestVectors.ipynb
  src/main/jupyter/oss/security/OssSecurityRatingTestVectors.ipynb
  src/main/jupyter/oss/security/OssSecurityScoreTestVectors.ipynb
  src/main/jupyter/oss/security/ProjectActivityScoreTestVectors.ipynb
  src/main/jupyter/oss/security/ProjectPopularityScoreTestVectors.ipynb
  src/main/jupyter/oss/security/ProjectSecurityAwarenessScoreTestVectors.ipynb
  src/main/jupyter/oss/security/ProjectSecurityTestingScoreTestVectors.ipynb
  src/main/jupyter/oss/security/README.md
  src/main/jupyter/oss/security/UnpatchedVulnerabilitiesScoreTestVectors.ipynb
  src/main/jupyter/oss/security/VulnerabilityLifetimeScoreTestVectors.ipynb
  src/main/jupyter/oss/security/commons.py
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExampleVerificationTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/CommunityCommitmentScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/CommunityCommitmentScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/LgtmScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/LgtmScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectPopularityScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectPopularityScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTestVectors.csv
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTestVectors.yml
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectorTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/VulnerabilitiesTest.java
Labels: enhancement

#103 Introduced a test suite for the demo tool
  CONTRIBUTING.md
  src/test/shell/tool/github/README.md
  src/test/shell/tool/github/run_tests.sh
  src/test/shell/tool/github/test_anonymous_connection.sh
  src/test/shell/tool/github/test_both_url_and_config.sh
  src/test/shell/tool/github/test_config.sh
  src/test/shell/tool/github/test_config.yml
  src/test/shell/tool/github/test_help.sh
  src/test/shell/tool/github/test_single_project.sh
Labels: test

#109 Updated the demo tool and data providers to use loggers
  pom.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/data/IsApache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/IsEclipse.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/Terminal.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/ValueCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/AbstractGitHubDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/FirstCommit.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasCompanySupport.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityPolicy.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityTeam.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfCommits.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfContributors.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfStars.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfWatchers.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/ProjectStarted.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/SecurityReviewForProject.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UnpatchedVulnerabilities.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommits.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSnykDependencyCheck.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/VulnerabilitiesFromNvd.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/lgtm/LgtmDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/format/PrettyPrinter.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/AbstractRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/AbstractReporter.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MarkdownReporter.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MergedJsonReporter.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MultipleSecurityRatingsCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculator.java
  src/main/resources/log4j2.xml
Labels: dependency, enhancement

#113 Introduced a feature that holds programming languages
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguages.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Feature.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Value.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/LanguagesFeature.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/OssFeatures.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/Language.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/Languages.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/LanguagesValue.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguagesTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/LanguagesFeatureTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/LanguagesValueTest.java
Labels: enhancement

#114 Introduced a feature for Dependabot
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabot.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/OssFeatures.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabotTest.java
Labels: enhancement

#119 Introduced a feature for package managers
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/PackageManagement.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Feature.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Value.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/OssFeatures.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/PackageManagersFeature.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/Language.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/Languages.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/PackageManager.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/PackageManagers.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/PackageManagersValue.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/PackageManagementTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguagesTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/PackageManagersFeatureTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/PackageManagersValueTest.java
Labels: enhancement

#112 Extended DataProvider interface
  src/main/java/com/sap/sgs/phosphor/fosstars/data/AbstractDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/CompositeDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/DataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/IsApache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/IsEclipse.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/NoCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/StandardValueCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/ValueCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/AbstractGitHubDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/FirstCommit.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasCompanySupport.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityPolicy.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityTeam.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/IsApache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/IsEclipse.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/LgtmDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfCommits.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfContributors.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfStars.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfWatchers.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/PackageManagement.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguages.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/ProjectStarted.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/SecurityReviewForProject.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UnpatchedVulnerabilities.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabot.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommits.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSnykDependencyCheck.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/VulnerabilitiesFromNvd.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/json/CompanySupportStorage.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/json/SecurityReviewStorage.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/json/SecurityTeamStorage.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/json/UnpatchedVulnerabilitiesStorage.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/AbstractRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubOrganization.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProject.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProjectCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProjectValueCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MultipleSecurityRatingsCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculator.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/CompositeDataProviderTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/StandardValueCacheTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityPolicyTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/LgtmDataProviderTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfContributorsTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/PackageManagementTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguagesTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabotTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyCheckTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/json/HasCompanySupportStorageTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/json/SecurityTeamStorageTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/MultipleSecurityRatingsCalculatorTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculatorTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/LgtmProjectDoesNotExistReply.json
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/LgtmProjectInfoReply.json
Labels: enhancement

#115 Added three unpatched vulnerabilities for odata4j
  src/main/java/com/sap/sgs/phosphor/fosstars/data/json/UnpatchedVulnerabilitiesStorage.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/data/UnpatchedVulnerabilities.json
  src/test/java/com/sap/sgs/phosphor/fosstars/data/json/UnpatchedVulnerabilitiesStorageTest.java
Labels: data

#120 Separate interactive data providers
  src/main/java/com/sap/sgs/phosphor/fosstars/data/CompositeDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/DataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/AbstractGitHubDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityTeam.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UnpatchedVulnerabilities.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/interactive/AbstractInteractiveDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/interactive/AskAboutSecurityTeam.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/interactive/AskAboutUnpatchedVulnerabilities.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/AbstractRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProject.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MultipleSecurityRatingsCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/RatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculator.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/CompositeDataProviderTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/interactive/AskAboutSecurityTeamTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/interactive/AskAboutUnpatchedVulnerabilitiesTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/interactive/TestUserCallback.java
Labels: enhancement

#125 Unifying the data gathering process for data providers
  pom.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/data/DataCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/AbstractGitHubDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/FirstCommit.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityPolicy.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfCommits.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfContributors.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfStars.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfWatchers.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/PackageManagement.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguages.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/ProjectStarted.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabot.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopment.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommits.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubDataCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubDataFetcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculator.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfContributorsTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/PackageManagementTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguagesTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabotTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopmentTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubDataCacheTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubDataFetcherTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitFalse.json
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitTrue.json
Labels: dependency, enhancement

#130 Introduced a feature for NoHTTP tool
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesNoHttpTool.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/oss/OssFeatures.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubDataFetcher.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesNoHttpToolTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubDataFetcherTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/GradleCheckStyleWithNoHTTP.gradle
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/GradleCheckStyleWithoutNoHTTP.gradle
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/MavenCheckStyleWithNoHTTP.xml
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/MavenCheckStyleWithoutNoHTTP.xml
Labels: enhancement

#132 Updated HasSecurityPolicyTest to use mocks
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityPolicyTest.java
Labels: test

#135 Move GitHubDataFetcher to the com.sap.sgs.phosphor.fosstars.data.github package
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/AbstractGitHubDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubCachingDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabot.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcherTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityPolicyTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfContributorsTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/PackageManagementTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/ProgrammingLanguagesTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabotTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopmentTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitTest.java
Labels: enhancement

#136 Improve cache in data providers
  src/main/java/com/sap/sgs/phosphor/fosstars/data/AbstractCachingDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/AbstractDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/Cache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/CompositeDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/NoCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/NoValueCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/StandardValueCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/ValueCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/CachedSingleFeatureGitHubDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/LgtmDataProvider.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/ValueSet.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/ValueHashSet.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/AbstractRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubOrganization.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProjectValueCache.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/AbstractCachingDataProviderTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/NoValueCacheTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/StandardValueCacheTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCacheTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcherTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/interactive/AskAboutSecurityTeamTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/interactive/AskAboutUnpatchedVulnerabilitiesTest.java
Labels: enhancement

#139 Make UsesGithubForDevelopment data provider smarter
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopment.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesGithubForDevelopmentTest.java
Labels: enhancement

#140 Pull vulnerabilities from GitHub Security Advisory Database
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/VulnerabilitiesFromGitHubAdvisories.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/GitHubAdvisories.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/Advisory.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/AdvisoryReference.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/Data.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/GitHubAdvisoryEntry.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/Identifier.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/Node.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/Package.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/PageInfo.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/SecurityAdvisories.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/data/SecurityVulnerabilities.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/first_run_template
  src/main/resources/com/sap/sgs/phosphor/fosstars/data/github/experimental/graphql/next_page_run_template
Labels: enhancement

#138 Look for unpatched vulnerabilities in NVD
  .gitignore
  checkstyle-suppressions.xml
  docs/oss/security/apache.yml
  docs/oss/security/eclipse.yml
  docs/oss/security/other.yml
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/InfoAboutVulnerabilities.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UnpatchedVulnerabilities.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/VendorDataMatcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/VulnerabilitiesFromNvd.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/Vulnerability.java
  src/main/java/com/sap/sgs/phosphor/fosstars/nvd/ExactMatcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/nvd/Matcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/nvd/NVD.java
  src/main/java/com/sap/sgs/phosphor/fosstars/nvd/data/CpeMatch.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/AbstractRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MultipleSecurityRatingsCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculator.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculator.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/data/UnpatchedVulnerabilities.json
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UnpatchedVulnerabilitiesTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/nvd/NVDTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/MultipleSecurityRatingsCalculatorTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculatorTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculatorTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/data/github/NVD_part_CVE-2014-0171.json
  src/test/resources/com/sap/sgs/phosphor/fosstars/nvd/NVD_part_2014.json
  src/test/resources/com/sap/sgs/phosphor/fosstars/tool/github/ValidSecurityRatingCalculatorConfig.yml
  src/test/shell/tool/github/test_config.sh
  src/test/shell/tool/github/test_config.yml
Labels: enhancement

#149 Simplify WeightedCompositeScore
  checkstyle-suppressions.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVector.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectorResult.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExample.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExampleTuningWithCMAES.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/WeightedCompositeScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/tuning/AbstractTuning.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/PackageManagers.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/weight/ScoreWeights.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProjectCache.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/SecurityRatingCalculator.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExample_1_1.json
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScore_1_0.json
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/WeightedCompositeScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/weight/ScoreWeightsTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/GitHubProjectCacheTest.java
  src/test/resources/com/sap/sgs/phosphor/fosstars/tool/github/TestProjectRatingCache.json
Labels: enhancement

#151 Implemented a collection of test vectors
  checkstyle-suppressions.xml
  pom.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/AbstractVerification.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/AbstractVerifier.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/RatingVerification.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/RatingVerifier.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/ScoreVerification.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/ScoreVerifier.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/StandardTestVector.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVector.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectorBuilder.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectorWithDefaults.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectors.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExampleTuningWithCMAES.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExampleVerification.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingVerification.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/CommunityCommitmentScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/LgtmScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/NoHttpToolScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTuningWithCMAES.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectPopularityScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/ValueHashSet.java
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/CommunityCommitmentScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/DependencyScanScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/LgtmScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/NoHttpToolScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectActivityScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectPopularityScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTestVectors.yml
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/RatingVerificationTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/RatingVerifierTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/ScoreVerificationTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/ScoreVerifierTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/StandardTestVectorTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectorBuilderTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectorResultTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/qa/TestVectorsTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/NoHttpToolScoreTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTuningWithCMAESTest.java
Labels: dependency, enhancement
