Repository SAP/fosstars-rating-core, pull requests merged in 2020-07, with the labels that each got.

#246 Make GitHubDataFetcher thread safe
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/FuzzedInOssFuzzTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcherTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/HasSecurityPolicyTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/NumberOfContributorsTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/TestGitHubDataFetcherHolder.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesDependabotTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesFindSecBugsTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesNoHttpToolTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyCheckTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSanitizersTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/UsesSignedCommitTest.java
Labels: enhancement

#255 WeightedCompositeScore should set weight for N/A sub-scores
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/WeightedCompositeScore.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/WeightedCompositeScoreTest.java
Labels: bug

#257 Cleanup task should remove project from LOCAL_REPOSITORIES
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcherTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/TestGitHubDataFetcherHolder.java
Labels: bug

#258 Add a label for unclear ratings
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/AbstractRating.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/example/SecurityRatingExample.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRating.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/github/MarkdownReporter.java
  src/main/jupyter/oss/security/SecurityRatingAnalysis.ipynb
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingThresholds.json
  src/test/java/com/sap/sgs/phosphor/fosstars/model/RatingRepositoryTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/MarkdownReporterTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/MultipleSecurityRatingsCalculatorTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/tool/github/SingleSecurityRatingCalculatorTest.java
Labels: enhancement

#271 Updated GitHubDataFetcher to reset changes before updating repositories
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/LocalRepository.java
Labels: bug

#274 Update weights in the open-source security score
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/rating/oss/OssSecurityRatingTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreTestVectors.yml
  src/main/resources/com/sap/sgs/phosphor/fosstars/model/score/oss/OssSecurityScoreWeights.json
Labels: tuning

#285 LgtmDataProvider may fail while retrieving check runs
  pom.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/LgtmDataProvider.java
Labels: bug, dependency

#286 Fix deserialization of EnumValue
  pom.xml
  src/main/java/com/sap/sgs/phosphor/fosstars/data/github/UsesOwaspDependencyScan.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/Feature.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/EnumFeature.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/EnumValue.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/feature/EnumFeatureTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/EnumValueTest.java
Labels: bug, dependency, enhancement

#287 FuzzedInOssFuzzTest should clean up
  src/test/java/com/sap/sgs/phosphor/fosstars/data/github/FuzzedInOssFuzzTest.java
Labels: bug, test

#288 PrettyPrinter should wrap score descriptions
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/VulnerabilityDiscoveryAndSecurityTestingScore.java
  src/main/java/com/sap/sgs/phosphor/fosstars/tool/format/PrettyPrinter.java
Labels: enhancement

#292 OwaspDependencyScanScore should expect unknown values
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OwaspDependencyScanScore.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/oss/OwaspDependencyScanScoreTest.java
Labels: bug

#289 Check for scores in FeatureBasedScore
  src/main/java/com/sap/sgs/phosphor/fosstars/model/score/FeatureBasedScore.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/score/FeatureBasedScoreTest.java
Labels: enhancement

#293 OwaspDependencyCheckCvssThresholdValue should contains a valid value
  src/main/java/com/sap/sgs/phosphor/fosstars/model/feature/OwaspDependencyCheckCvssThreshold.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/CVSS.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/DoubleValue.java
  src/main/java/com/sap/sgs/phosphor/fosstars/model/value/OwaspDependencyCheckCvssThresholdValue.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/CvssTest.java
  src/test/java/com/sap/sgs/phosphor/fosstars/model/value/OwaspDependencyCheckCvssThresholdValueTest.java
Labels: enhancement
