Repository SAP/fosstars-rating-core, pull requests merged in 2021-05, with the labels that each got.

#513 Make AbstractValue.isUnknown() final
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/AbstractValue.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionsValue.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/NotApplicableValue.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/VulnerabilitiesValue.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/artifact/ReleaseInfoLoaderTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/ReleasesFromGitHubTest.java
Labels: enhancement

#505 Refactor Artifact / ArtifactVersion / ArtifactVersionFeature
  src/main/java/com/sap/oss/phosphor/fosstars/advice/oss/ArtifactVersionAdvisor.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/AbstractReleaseInfoLoader.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/ReleaseInfoFromMaven.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/ReleaseInfoFromNpm.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/ReleaseInfoLoader.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/ReleasesFromGitHub.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Feature.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Value.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/StringFeature.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/oss/ArtifactVersionFeature.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/oss/OssFeatures.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactLatestReleaseAgeScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactReleaseHistoryScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionUpToDateScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionVulnerabilityScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/subject/oss/MavenArtifact.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/subject/oss/NpmArtifact.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersion.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionValue.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/SemanticVersion.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/github/Application.java
  src/test/java/com/sap/oss/phosphor/fosstars/TestUtils.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/artifact/ReleaseInfoFromMavenTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/artifact/ReleaseInfoFromNpmTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/artifact/ReleaseInfoLoaderTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/feature/StringFeatureTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/feature/oss/ArtifactVersionFeatureTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/rating/oss/TestArtifactVersion.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactLatestReleaseAgeScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactReleaseHistoryScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionUpToDateScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionVulnerabilityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/subject/oss/MavenArtifactTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/subject/oss/NpmArtifactTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionValueTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionsTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionsValueTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/StringValueTest.java
  src/test/resources/com/sap/oss/phosphor/fosstars/model/rating/oss/OssArtifactSecurityRatingTestVectors.yml
Labels: enhancement

#521 rl-contributor_file-2 should be a warning in the OSS RoP rating
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssRulesOfPlayScore.java
Labels: bug

#530 Smarter CpeMatch.getCpeUri()
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/NvdEntryMatcher.java
  src/main/java/com/sap/oss/phosphor/fosstars/nvd/NVD.java
  src/main/java/com/sap/oss/phosphor/fosstars/nvd/data/CpeMatch.java
Labels: bug

#520 PackageManagers.containsAny() should expect an empty list
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/PackageManagers.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/PackageManagersTest.java
Labels: bug

#516 Flexible serialization for implementations of main interfaces
  src/main/java/com/sap/oss/phosphor/fosstars/model/Feature.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Interval.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Label.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Rating.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Score.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Value.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/ValueSet.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Weight.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/StringFeature.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/qa/TestVector.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/subject/oss/Artifact.java
  src/main/java/com/sap/oss/phosphor/fosstars/util/Deserialization.java
  src/main/java/com/sap/oss/phosphor/fosstars/util/Json.java
  src/main/java/com/sap/oss/phosphor/fosstars/util/Yaml.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/feature/StringFeatureTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScoreTest.java
Labels: enhancement

#555 HasSecurityPolicyTest.noTestPolicy() should not require access to the Internet
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/HasSecurityPolicyTest.java
Labels: bug, test

#550 Use GitHub License API in License Info data provider
  .gitignore
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/LicenseInfo.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/oss/OssFeatures.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/LicenseInfoTest.java
Labels: enhancement

#560 OSS RoP: Add repository exceptions for license check
  LicenseInfo.config.yml
Labels: RoP, configuration

#561 Added parameters for OSS RoP workflow
  .github/workflows/fosstars-rules-of-play.yml
Labels: enhancement

#549 Add technique to compare semantic versions
  pom.xml
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactReleaseHistoryScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersion.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersions.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/SemanticVersion.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactReleaseHistoryScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionsTest.java
Labels: enhancement
