Repository SAP/fosstars-rating-core, pull requests merged in 2021-06, with the labels that each got.

#575 Fixes sorting comparator bug
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersion.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersions.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/ArtifactVersionsTest.java
Labels: bug

#534 OWASP Dependency Check integration with Maven artifact
  pom.xml
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/VulnerabilitiesFromOwaspDependencyCheck.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/Cvssv2.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/Cvssv3.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/Dependency.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/OwaspDependencyCheckEntry.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/OwaspDependencyCheckReference.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/OwaspDependencyCheckVuln.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/Software.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/VulnerableSoftware.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/experimental/owasp/data/package-info.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/oss/OssFeatures.java
Labels: poc

#593 Fix missing recommendations for the OSS security rating
  src/main/java/com/sap/oss/phosphor/fosstars/advice/oss/github/OssSecurityGithubAdvisor.java
Labels: bug

#595 OSS Rules of Play gets option to create issues for findings
  .gitignore
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/GitHubDataFetcher.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/format/AbstractMarkdownFormatter.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/format/CommonFormatter.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/format/Formatter.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/format/OssRulesOfPlayRatingMarkdownFormatter.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/github/Application.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/report/OssRulesOfPlayMarkdownReporter.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/GitHubDataFetcherTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/format/OssRulesOfPlayRatingMarkdownFormatterTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/format/OssSecurityRatingMarkdownFormatterTest.java
Labels: enhancement

#607 Fix NPE in LicenseInfo
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/LicenseInfo.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/LicenseInfoTest.java
Labels: bug

#606 Better OSS RoP action
  .github/actions/oss-rules-of-play-action/entrypoint.sh
Labels: bug

#612 Documentation for OSS rules of play rating
  docs/README.md
  docs/alternatives.md
  docs/getting_oss_rules_of_play_rating.md
  docs/getting_oss_security_rating.md
  docs/oss_rules_of_play_rating.md
  src/main/java/com/sap/oss/phosphor/fosstars/tool/Application.java
Labels: documentation
