Repository SAP/fosstars-rating-core, pull requests merged in 2021-08, with the labels that each got.

#659 Use ROP_TOKEN in the fosstars-rop-report.yml workflow
  .github/workflows/fosstars-rop-report.yml
Labels: enhancement

#664 RoP docs: Add information on token permissions
  docs/getting_oss_rules_of_play_rating.md
Labels: documentation

#662 Fail gracefully when issues are disabled
  src/main/java/com/sap/oss/phosphor/fosstars/tool/report/OssRulesOfPlayGitHubIssuesReporter.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/report/OssRulesOfPlayGitHubIssuesReporterTest.java
Labels: bug

#669 Increase the cluster threshold
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactReleaseHistoryScore.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactReleaseHistoryScoreTest.java
Labels: tuning

#668 Added --pom option for CLI
  src/main/java/com/sap/oss/phosphor/fosstars/maven/GAV.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/AbstractHandler.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/Application.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/MavenScmFinder.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/OssProjectSecurityRatingHandler.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/report/OssSecurityRatingMarkdownReporter.java
  src/test/shell/tool/github/test_project_security_with_pom.sh
  src/test/shell/tool/github/test_project_security_with_pom.xml
Labels: enhancement

#673 OSS security scoring function should return an unknown value for all …
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/AbstractScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/CommunityCommitmentScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/DependabotScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/FuzzingScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/MemorySafetyTestingScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/NoHttpToolScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OwaspDependencyScanScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ProjectPopularityScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/SecurityReviewScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityDiscoveryAndSecurityTestingScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScore.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/rating/oss/OssSecurityRatingTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/CodeqlScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/CommunityCommitmentScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/DependabotScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/DependencyScanScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/FindSecBugsScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/FuzzingScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/LgtmScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/MemorySafetyTestingScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/NoHttpToolScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OwaspDependencyScanScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ProjectActivityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ProjectPopularityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ProjectSecurityAwarenessScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ProjectSecurityTestingScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/SecurityReviewScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/StaticAnalysisScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityDiscoveryAndSecurityTestingScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/MultipleRatingsCalculatorTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/SingleRatingCalculatorTest.java
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/CommunityCommitmentScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/DependencyScanScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/FuzzingScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/MemorySafetyTestingScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/NoHttpToolScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/ProjectPopularityScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/SecurityReviewScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityDiscoveryAndSecurityTestingScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTestVectors.yml
Labels: bug

#676 GitHub issue creation: Use identifer only for existence check
  src/main/java/com/sap/oss/phosphor/fosstars/tool/report/OssRulesOfPlayGitHubIssuesReporter.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/report/OssRulesOfPlayGitHubIssuesReporterTest.java
Labels: enhancement

#680 RoP documentation: Add explanation about licenses
  docs/oss_rules_of_play_rating.md
Labels: documentation, RoP

#682 RoP: Also search for lowercase READMEs
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/ReadmeInfo.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/ReadmeInfoTest.java
Labels: bug, RoP
