Repository SAP/fosstars-rating-core, pull requests merged in 2021-07, with the labels that each got.

#623 Update LicenseInfo.config.yml
  LicenseInfo.config.yml
Labels: RoP, configuration

#628 Add licensee info to troubleshoot license detection issues
  docs/oss_rules_of_play_rating.md
Labels: documentation

#636 RoP: Add README.rst & check REUSE case-insensitively
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/ReadmeInfo.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/UseReuseDataProvider.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/ReadmeInfoTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/UseReuseDataProviderTest.java
Labels: bug

#640 RoP: Follow symbolic links for REUSE licenses
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/UseReuseDataProvider.java
Labels: bug

#638 Fixes JSON mapping infinite recursion loop
  checkstyle-suppressions.xml
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/SecurityReview.java
  src/test/java/com/sap/oss/phosphor/fosstars/TestUtils.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSFTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/SecurityReviewScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/SecurityReviewTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/SecurityReviewsTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/SecurityReviewsValueTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/format/OssSecurityRatingMarkdownFormatterTest.java
Labels: bug

#641 Added hashCode() for a few base value classes
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/AbstractKnownValue.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/UnknownValue.java
Labels: enhancement

#648 RoP docs: Explain the rationale for the RoP
  docs/oss_rules_of_play_rating.md
Labels: documentation

#654 Don't load data from NVD for RoP
  src/main/java/com/sap/oss/phosphor/fosstars/tool/AbstractHandler.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/OssProjectSecurityRatingHandler.java
Labels: bug

#657 Add a workflow for RoP
  .github/workflows/fosstars-rop-report.yml
  README.md
Labels: enhancement

#652 Added a workflow for renewing OSS security report
  .github/actions/project-security-label-threshold-action/Dockerfile
  .github/actions/project-security-label-threshold-action/action.yml
  .github/actions/project-security-label-threshold-action/entrypoint.sh
  .github/actions/project-security-report-action/Dockerfile
  .github/actions/project-security-report-action/action.yml
  .github/actions/project-security-report-action/build_fosstars.sh
  .github/actions/project-security-report-action/cleanup_for_config_if_necessary.sh
  .github/actions/project-security-report-action/entrypoint.sh
  .github/workflows/oss-projects-security-label-thresholds.yml
  .github/workflows/oss-projects-security-report.yml
  src/main/jupyter/oss/security/SecurityRatingAnalysis.ipynb
Labels: enhancement

#656 Use VULNERABILITIES_IN_ARTIFACT feature in the artifact security rating
  src/main/java/com/sap/oss/phosphor/fosstars/data/DataProviderSelector.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromOwaspDependencyCheck.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/InfoAboutVulnerabilities.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/UnpatchedVulnerabilities.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/VulnerabilitiesFromNvd.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/experimental/VulnerabilitiesFromGitHubAdvisories.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/interactive/AskAboutUnpatchedVulnerabilities.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/Cvssv2.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/Cvssv3.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/Dependency.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/OwaspDependencyCheckEntry.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/OwaspDependencyCheckReference.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/OwaspDependencyCheckVuln.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/Software.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/VulnerableSoftware.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/owasp/model/package-info.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/oss/OssFeatures.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/feature/oss/VulnerabilitiesFeature.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionVulnerabilityScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityDiscoveryAndSecurityTestingScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScore.java
  src/main/java/com/sap/oss/phosphor/fosstars/model/value/VulnerabilitiesValue.java
  src/main/java/com/sap/oss/phosphor/fosstars/tool/format/CommonFormatter.java
  src/main/java/com/sap/oss/phosphor/fosstars/util/Deserialization.java
  src/test/java/com/sap/oss/phosphor/fosstars/TestUtils.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromOwaspDependencyCheckTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/interactive/AskAboutUnpatchedVulnerabilitiesTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/feature/oss/VulnerabilitiesFeatureTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactVersionVulnerabilityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssSecurityScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityDiscoveryAndSecurityTestingScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/value/VulnerabilitiesValueTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/format/OssSecurityRatingMarkdownFormatterTest.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/format/PrettyPrinterTest.java
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/OwaspDependencyHasNoVulnerabilities.json
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromOwaspDependencyCheck.json
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromOwaspNoDependencies.json
  src/test/resources/com/sap/oss/phosphor/fosstars/model/rating/oss/OssArtifactSecurityRatingTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/rating/oss/OssSecurityRatingTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/UnpatchedVulnerabilitiesScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityDiscoveryAndSecurityTestingScoreTestVectors.yml
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/VulnerabilityLifetimeScoreTestVectors.yml
Labels: enhancement
