Repository SAP/fosstars-rating-core, pull requests merged in 2022-06, with the labels that each got.

#822 Addressing IllegalStateException in OssArtifactSecurityScore
  pom.xml
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScore.java
  src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScoreTest.java
Labels: bug

#825 Add organization name to rules of play report findings
  src/main/java/com/sap/oss/phosphor/fosstars/tool/report/OssRulesOfPlayMarkdownReporter.java
  src/test/java/com/sap/oss/phosphor/fosstars/tool/report/OssRulesOfPlayMarkdownReporterTest.java
Labels: bug

#829 Release list should be filtered for nulls
  src/main/java/com/sap/oss/phosphor/fosstars/data/github/ReleasesFromGitHub.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/github/ReleasesFromGitHubTest.java
Labels: bug

#823 Address Non-Deterministic Behavior in Unit Test
  src/test/java/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromOwaspDependencyCheckTest.java
Labels: test

#834 Prepare for 1.10.0-SNAPSHOT
  README.md
  pom.xml
Labels: snapshot
