Repository SAP/fosstars-rating-core, pull requests merged in 2022-01, with the labels that each got.

#745 Adding comparison to OSSF Scorecard
  docs/alternatives.md
  docs/compare_with_score-card.md
Labels: documentation

#767 Gather vulnerabilities from NPM audit
  checkstyle-suppressions.xml
  src/main/java/com/sap/oss/phosphor/fosstars/data/DataProviderSelector.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/NvdEntryArtifactCveMatcher.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromNpmAudit.java
  src/main/java/com/sap/oss/phosphor/fosstars/data/npmaudit/model/Advisory.java
  src/main/java/com/sap/oss/phosphor/fosstars/nvd/NVD.java
  src/test/java/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromNpmAuditTest.java
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/NoCvesFromNpmAudit.json
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/NoPatchForAdvisory.json
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/NotAllCvesFromNpmAudit.json
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/NpmVulnerabilitiesFromNvd.json
  src/test/resources/com/sap/oss/phosphor/fosstars/data/artifact/VulnerabilitiesFromNpmAudit.json
  src/test/resources/com/sap/oss/phosphor/fosstars/model/score/oss/SecurityReviewScoreTestVectors.yml
Labels: enhancement

#769 Rectify project rating score in artifact rating score
  src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScore.java
  src/test/resources/com/sap/oss/phosphor/fosstars/model/rating/oss/OssArtifactSecurityRatingTestVectors.yml
Labels: bug
